### ISSUE TITLE
Missing menu link for Task Scheduling

### ISSUE THREAD

**Issue by fschirinzi** [laravel-zero/docs#23]
The page for [Task Scheduling](https://laravel-zero.com/docs/task-scheduling) exists, but is not listed in the sidebar menu.
Maybe it should be added? :)

**Comment by owenvoke** [comment]
Thanks for flagging this up. 👍🏻 Feel free to PR the change, otherwise I'll resolve this later today.

**Comment by owenvoke** [comment]
Closed by #24
